;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

(load! "style.el")
(load! "dashboard.el")
(load! "personal.el")
(load! "dird.el")
(load! "lang.el")
(load! "cli.el")
(load! "quickmove.el")
(load! "search.el")
(load! "web.el")
(load! "term.el")
(load! "posframe.el")
(load! "util.el")
(load! "other.el")
(load! "packages.el")
;; (load! "org.el")
(load! "key.el")
(load! "custom.el")
